fullnameOverride: ftdreceiver

deployment:
  enabled: true
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  annotations:
    deployment.kubernetes.io/revision: "1"
  podAnnotations:
    prometheus.io/path: /manage/prometheus
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
    redeploytrigger: xxxx
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - ftdreceiver
            topologyKey: topology.kubernetes.io/zone
        - weight: 5
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - ftdreceiver
            topologyKey: kubernetes.io/hostname
  hostAliases:
    - ip: x.x.x.x
      hostnames:
        - xxxxx.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxxx-secondary.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxx.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxx.redis.cache.windows.net
  terminationGracePeriodSeconds: 60
  serviceAccount:
    automount: false

containers:
  - name: ftdreceiver
    image: docker.repo.xxx.xxx/servicecatalog/ftd-receiver:1.31.7-saas-202509041300
    imagePullPolicy: Always
    ports:
      - name: serviceport
        containerPort: 8080
        protocol: TCP
    env:
      - name: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=60.0 -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -XX:+UseStringDeduplication
      - name: LOGGING_LEVEL_COM_XXX
        value: INFO
      - name: SERVER_PORT
        value: "8080"
      - name: MANAGEMENT_SERVER_PORT
        value: "8081"
      - name: SERVER_SERVLET_CONTEXT_PATH
        value: /ftdreceiver
      - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
        value: xxxx.servicebus.windows.net:9093
      - name: KAFKA_CONFIG_CHARGING_POSITION_TOPIC_NAME
        value: charging-position
      - name: POSITION_PROCESSING_FUTURE_TIME_LIMIT
        value: 30d
    envFrom:
      - secretRef:
          name: ftdreceiver-secret
    lifecycle:
      preStop:
        exec:
          command: ["sleep", "20"]
    resources:
      limits:
        cpu: 300m
        memory: 896Mi
        ephemeral-storage: 1Gi
      requests:
        cpu: 100m
        memory: 896Mi
        ephemeral-storage: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
    probes:
      liveness:
        httpGet:
          path: /manage/health
          port: 8081
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 10
      readiness:
        httpGet:
          path: /manage/health
          port: 8081
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 5
      startup:
        httpGet:
          path: /manage/health
          port: 8081
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 7

service:
  enabled: true
  type: ClusterIP
  clusterIP: 10.224.78.244
  ports:
    - name: serviceport
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: healthport
      port: 8081
      targetPort: 8081
      protocol: TCP
  sessionAffinity: None

secrets:
  enabled: true
  type: Opaque
  data:
    AZMON_COLLECT_ENV: xxx=
    KAFKA_PASSWORD: xxxx
    KAFKA_USER: xxx=

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: ContainerResource
      containerResource:
        container: ftdreceiver
        name: cpu
        target:
          type: AverageValue
          averageValue: 210m
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      selectPolicy: Max
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 180

networkPolicy:
  enabled: true
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app: ftdreceiver
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: k8s-ansible-helper
        - podSelector:
            matchLabels:
              app: kong
      ports:
        - port: 8080
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              kubernetes.azure.com/managedby: aks
        - podSelector:
            matchLabels:
              app: k8s-ansible-helper
      ports:
        - port: 8081
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 9093
          protocol: TCP
