app: ftdreceiver
deployment_commit: 09df525f
deployment_ref: xx-14530-be--env01

replicaCount: 1
image:
  repository: docker.repo.xxx.xxx/servicecatalog/ftd-receiver
  tag: 1.31.7-saas-202509041300

containerPorts:
  - name: serviceport
    port: 8080
    protocol: TCP

env:
  - name: JAVA_TOOL_OPTIONS
    value: -XX:MaxRAMPercentage=60.0 -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -XX:+UseStringDeduplication
  - name: LOGGING_LEVEL_COM_XXX
    value: INFO
  - name: SERVER_PORT
    value: "8080"
  - name: MANAGEMENT_SERVER_PORT
    value: "8081"
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /ftdreceiver
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: xxxx.servicebus.windows.net:9093
  - name: KAFKA_CONFIG_CHARGING_POSITION_TOPIC_NAME
    value: charging-position
  - name: POSITION_PROCESSING_FUTURE_TIME_LIMIT
    value: 30d

envFrom:
  - secretRef:
      name: ftdreceiver-secret

resources:
  limits:
    cpu: 300m
    memory: 896Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 100m
    memory: 896Mi
    ephemeral-storage: 1Gi

lifecycle:
  preStop:
    exec:
      command: ["sleep", "20"]

livenessProbe:
  httpGet:
    path: /manage/health
    port: 8081
    scheme: HTTP
  initialDelaySeconds: 3
  periodSeconds: 20
  timeoutSeconds: 20
  successThreshold: 1
  failureThreshold: 10

readinessProbe:
  httpGet:
    path: /manage/health
    port: 8081
    scheme: HTTP
  initialDelaySeconds: 3
  periodSeconds: 20
  timeoutSeconds: 20
  successThreshold: 1
  failureThreshold: 5

startupProbe:
  httpGet:
    path: /manage/health
    port: 8081
    scheme: HTTP
  initialDelaySeconds: 3
  periodSeconds: 20
  timeoutSeconds: 20
  successThreshold: 1
  failureThreshold: 7

hostAliases:
  - ip: x.x.x.x
    hostnames:
      - xxxxx.blob.core.windows.net
      - xxxxx-secondary.blob.core.windows.net
      - xxxx.blob.core.windows.net
      - xxxx.redis.cache.windows.net

terminationGracePeriodSeconds: 60

service:
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  ipFamily: IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: serviceport
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: healthport
      port: 8081
      protocol: TCP
      targetPort: 8081

autoscaling:
  enabled: true
  container: ftdreceiver
  minReplicas: 1
  maxReplicas: 4
  targetCPUAverageValue: 210m
  scaleUp:
    pods: 2
    periodSeconds: 60
    selectPolicy: Max
    stabilizationWindowSeconds: 60
  scaleDown:
    pods: 1
    periodSeconds: 180
    selectPolicy: Max
    stabilizationWindowSeconds: 300

networkPolicy:
  enabled: true
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: k8s-ansible-helper
        - podSelector:
            matchLabels:
              app: kong
      ports:
        - port: 8080
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              kubernetes.azure.com/managedby: aks
        - podSelector:
            matchLabels:
              app: k8s-ansible-helper
      ports:
        - port: 8081
          protocol: TCP
  egress:
    - ports:
        - port: 53
          protocol: UDP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              k8s-app: kube-dns
    - ports:
        - port: 9093
          protocol: TCP
      to:
        - ipBlock:
            cidr: 0.0.0.0/0

secret:
  enabled: true
  data:
    AZMON_COLLECT_ENV: xxx=
    KAFKA_PASSWORD: xxxx
    KAFKA_USER: xxx=
