fullnameOverride: positianstream

deployment:
  enabled: true
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  annotations:
    deployment.kubernetes.io/revision: "1"
  podAnnotations:
    prometheus.io/path: /manage/prometheus
    prometheus.io/port: "8090"
    prometheus.io/scrape: "true"
    redeploytrigger: 74f600219189eaf8474de12312c9419b8b588f12
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - positianstream
            topologyKey: topology.kubernetes.io/zone
        - weight: 5
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - positianstream
            topologyKey: kubernetes.io/hostname
  hostAliases:
    - ip: x.x.x.x
      hostnames:
        - xxxxx.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxxx-secondary.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxx.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxx.redis.cache.windows.net
  terminationGracePeriodSeconds: 60
  serviceAccount:
    automount: false

containers:
  - name: positianstream
    image:
      repository: xx
      tag: xx
    imagePullPolicy: Always
    ports:
      - name: serviceport
        containerPort: 8090
        protocol: TCP
    env:
      - name: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=60.0 -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -XX:+UseStringDeduplication
      - name: LOGGING_LEVEL_COM_XXX
        value: INFO
      - name: MANAGEMENT_SERVER_PORT
        value: "8090"
      - name: SPRING_PROFILES_ACTIVE
      - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: info,health,prometheus
      - name: POSITIAN_CLEANEXPIREDDEVICES_CRON
        value: 0 * * * * ?
      - name: POSITIAN_CLEANEXPIREDDEVICES_EXPIRATIONAGE
        value: PT60m
      - name: POSITIAN_CLEANEXPIREDDEVICES_EVICTIONAGE
        value: PT24h
      - name: RNS_MATCHTRACKSENDPOINTURL
        value: http://roadnetworkservice:8090/roadnetwork/europe/v1/matchtracks
      - name: RNS_CONNECTION_POOL_SIZE
        value: "64"
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: xxxx.servicebus.windows.net:9093
      - name: KAFKA_CONSUMER_CHARGINGPOSITIONTOPIC_NAME
        value: charging-position
      - name: KAFKA_CONSUMER_CHARGINGPOSITIONTOPIC_CONCURRENCY
        value: "32"
      - name: KAFKA_CONSUMER_CIRCUITBREAKER_ENABLED
        value: "true"
      - name: KAFKA_CONSUMER_CIRCUITBREAKER_PARTITIONMAXFAILURES
        value: "10"
      - name: KAFKA_CONSUMER_CIRCUITBREAKER_PARTITIONFAILURESWINDOW
        value: "100"
      - name: KAFKA_PRODUCER_MATCHEDROUTETOPIC_NAME
        value: matched-route
      - name: KAFKA_PRODUCER_MATCHEDPOSITIONTOPIC_NAME
        value: matched-position
      - name: KAFKA_PRODUCER_DEADLETTERTOPIC_NAME
        value: charging-position-dlt
      - name: SPRING_DATA_REDIS_HOST
        value: xxxx.redis.cache.windows.net
      - name: SPRING_DATA_REDIS_PORT
        value: "6379"
      - name: SPRING_DATA_REDIS_SSL_ENABLED
        value: "false"
      - name: SPRING_DATA_REDIS_DATABASE
        value: "1"
      - name: REDIS_CUSTOM_KEY_PREFIX
    envFrom:
      - secretRef:
          name: positianstream-secret
    lifecycle:
      preStop:
        exec:
          command: ["sleep", "20"]
    resources:
      limits:
        cpu: 800m
        memory: 1280Mi
        ephemeral-storage: 1Gi
      requests:
        cpu: 266m
        memory: 1280Mi
        ephemeral-storage: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
    probes:
      liveness:
        httpGet:
          path: /manage/health
          port: 8090
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 10
      readiness:
        httpGet:
          path: /manage/health
          port: 8090
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 5
      startup:
        httpGet:
          path: /manage/health
          port: 8090
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 7

service:
  enabled: true
  type: ClusterIP
  clusterIP: x.x.x.x
  ports:
    - name: serviceport
      port: 8090
      targetPort: 8090
      protocol: TCP
  sessionAffinity: None

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: ContainerResource
      containerResource:
        container: positianstream
        name: cpu
        target:
          type: AverageValue
          averageValue: 480m
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      selectPolicy: Max
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 180

networkPolicy:
  enabled: true
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app: positianstream
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              kubernetes.azure.com/managedby: aks
        - podSelector:
            matchLabels:
              app: k8s-ansible-helper
      ports:
        - port: 8090
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 9093
          protocol: TCP
        - port: 6379
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: roadnetworkservice
      ports:
        - port: 8090
          protocol: TCP

secrets:
  enabled: true
  type: Opaque
  data:
    AZMON_COLLECT_ENV: xx=
    KAFKA_PASSWORD: xx
    KAFKA_USER: xxx=
    SPRING_DATA_REDIS_PASSWORD: xx=
