k8ssandra-operator:
  # Set Scope for operator
  global:
    clusterScoped: true
    watchNamespaces:
      - cassandra-cluster
      - cassandra
      - k8ssandra

  # Set Replicas for Operator
  replicaCount: 3

  # Resources (optional tuning)
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
