k8ssandra-operator:
  # Resources (optional tuning)
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # Annotations (set to second sync wave for argocd)
  commonAnnotations:
    argocd.argoproj.io/sync-wave: "2"
