kafkaCluster:
  name: kdp-kafka-cluster
  annotations:
    nodePools: enabled
    kraft: enabled
    pauseReconciliation: "false"
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      log.segment.bytes: 1073741824
      log.retention.hours: 168
      log.retention.check.interval.ms: 300000
    # resources: {}
    # logging: {}
    # readinessProbe: {}
    # livenessProbe: {}
    # jvmOptions: {}
    # authorization: {}
  entityOperator:
    enabled: true
    topicOperator:
      topicOperator:
      watchedNamespace: kafka-topics
      reconciliationIntervalMs: 60000
      # Resources requests and limits
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
      # Logging configuration
      logging: # (23)
        type: inline
        loggers:
          rootLogger.level: INFO
    userOperator:
      watchedNamespace: kafka-topics
      reconciliationIntervalMs: 60000
      # Resources requests and limits
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
      # Logging configuration
      logging: # (24)
        type: inline
        loggers:
          rootLogger.level: INFO
  kafkaExporter:
    enabled: true
    topicRegex: ".*"
    groupRegex: ".*"

  cruiseControl:
    enabled: true
    templates:
      - name: add-brokers-template
      - name: remove-brokers-template

  nodePools:
    - name: kdp-kafka-cluster-controller
      roles: [controller]
      replicas: 3
      kafkaRole: controller
      # jvmOptions:
      #   xms: 3g
      #   xmx: 3g
      #   xx:
      #     "MetaspaceSize": "96m"
      #     "UseG1GC": "true"
      #     "MaxGCPauseMillis": "20"
      #     "InitiatingHeapOccupancyPercent": "35"
      #     "G1HeapRegionSize": "16M"
      #     "MinMetaspaceFreeRatio": "50"
      #     "MaxMetaspaceFreeRatio": "80"
      #     "ExplicitGCInvokesConcurrent": "true"
      # template:
      #   pod:
      #     metadata:
      #       labels:
      #         kafkaRole: controller
      #     affinity:
      #       nodeAffinity:
      #         requiredDuringSchedulingIgnoredDuringExecution:
      #           nodeSelectorTerms:
      #             - matchExpressions:
      #                 - key: app
      #                   operator: In
      #                   values: [kafka]
      #       podAffinity:
      #         preferredDuringSchedulingIgnoredDuringExecution:
      #           - weight: 100
      #             podAffinityTerm:
      #               labelSelector:
      #                 matchLabels:
      #                   kafkaRole: broker
      #               topologyKey: kubernetes.io/hostname
      #     topologySpreadConstraints:
      #       - labelSelector:
      #           matchLabels:
      #             kafkaRole: controller
      #         maxSkew: 1
      #         topologyKey: topology.kubernetes.io/zone
      #         whenUnsatisfiable: ScheduleAnyway
      #       - labelSelector:
      #           matchLabels:
      #             kafkaRole: controller
      #         maxSkew: 1
      #         topologyKey: kubernetes.io/hostname
      #         whenUnsatisfiable: ScheduleAnyway
      storage:
        type: jbod
        volumes:
          - id: 0
            type: persistent-claim
            size: 1Gi
            kraftMetadata: shared
            deleteClaim: false
    - name: kdp-kafka-cluster-broker
      roles: [broker]
      replicas: 3
      kafkaRole: broker
      # jvmOptions:
      #   xms: 6g
      #   xmx: 6g
      #   xx:
      #     "MetaspaceSize": "96m"
      #     "UseG1GC": "true"
      #     "MaxGCPauseMillis": "20"
      #     "InitiatingHeapOccupancyPercent": "35"
      #     "G1HeapRegionSize": "16M"
      #     "MinMetaspaceFreeRatio": "50"
      #     "MaxMetaspaceFreeRatio": "80"
      #     "ExplicitGCInvokesConcurrent": "true"
      # template:
      #   pod:
      #     metadata:
      #       labels:
      #         kafkaRole: broker
      #     affinity:
      #       nodeAffinity:
      #         requiredDuringSchedulingIgnoredDuringExecution:
      #           nodeSelectorTerms:
      #             - matchExpressions:
      #                 - key: app
      #                   operator: In
      #                   values:
      #                     - kafka
      #       podAffinity:
      #         preferredDuringSchedulingIgnoredDuringExecution:
      #           - weight: 100
      #             podAffinityTerm:
      #               labelSelector:
      #                 matchLabels:
      #                   kafkaRole: controller
      #               topologyKey: kubernetes.io/hostname
      #     topologySpreadConstraints:
      #       - labelSelector:
      #           matchLabels:
      #             kafkaRole: broker
      #         maxSkew: 1
      #         topologyKey: topology.kubernetes.io/zone
      #         whenUnsatisfiable: ScheduleAnyway
      #       - labelSelector:
      #           matchLabels:
      #             kafkaRole: broker
      #         maxSkew: 1
      #         topologyKey: kubernetes.io/hostname
      #         whenUnsatisfiable: ScheduleAnyway
      storage:
        type: jbod
        volumes:
          - id: 0
            type: persistent-claim
            size: 1Gi
            deleteClaim: true
