strimzi:
  # Namespace(s) the operator should watch, only specify the one's where the cluster is/will be isntalled.
  watchNamespaces:
    - kafka
    - strimzi

  # Set Replicas for operator
  replicas: 3

  # Logging configuration
  logLevel: DEBUG

  # Feature gates (optional)
  #featureGates: []

  # Resources (optional tuning)
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 384Mi
  # # Image override (optional)
  # image:
  #   registry: quay.io
  #   repository: strimzi/operator
  #   tag: 0.47.0

  # extraEnvs:
  #   - name: JAVA_OPTS
  #     value: "-Xms256m -Xmx256m"
