# Updated enterprise-ready values.yaml aligned with latest K8ssandraClusterSpec
#namespace: "k8ssandra" #"cassandra-cluster"
# annotations: {}
# labels: {}

# Authentication: whether authentication is enabled for Cassandra & auxiliary components
# auth: "false"

# secrets handling: operator will expect secrets in-cluster when using external provider
# secretsProvider: internal

prometheus:
  enabled: false

# Cassandra top-level settings
cassandra:
  clusterName: "kdp-addon-cassandra-cluster"
  serverVersion: "4.1.10"
  # softPodAntiAffinity: true
  metadata:
    annotations:
      {
        argocd.argoproj.io/tracking-id: app-k8ssandra:k8ssandra.io/K8ssandraCluster:k8ssandra/app-k8ssandra,
      }
  persistence:
    storageClassName: standard
    size: 10Gi
  # mgmtAPIHeap: "512Mi"
  # resources:
  #   requests:
  #     cpu: "2"
  #     memory: "4Gi"
  #   limits:
  #     cpu: "8"
  #     memory: "8Gi"
  config:
    cassandraYaml:
      read_request_timeout: 15000ms
      write_request_timeout: 15000ms
      counter_write_request_timeout: 15000ms
      request_timeout: 15000ms
      concurrent_reads: 16
      concurrent_writes: 16
    jvmOptions:
      heap_initial_size: 512M
      heap_max_size: 4096M

datacenters:
  - name: prod-dc-glp
    # metadata:
    #   annotations:
    #     {
    #       argocd.argoproj.io/tracking-id: app-k8ssandra:k8ssandra.io/K8ssandraCluster:k8ssandra/app-k8ssandra,
    #     }
    # managementApiAuth:
    #   insecure: {}
    size: 3
    persistence:
      storageClassName: standard
      size: 10Gi
    config:
      jvmOptions:
        heapSize: 512M

stargate:
  enabled: false

# Reaper (repairs) settings
reaper:
  enabled: true
  metadata:
    annotations:
      {
        argocd.argoproj.io/tracking-id: app-k8ssandra:k8ssandra.io/K8ssandraCluster:k8ssandra/app-k8ssandra,
      }
  # autoScheduling:
  #   enabled: false
  heapSize: 256Mi
  # httpManagement:
  #   enabled: false

# Medusa backups
medusa:
  enabled: true
  storageProperties:
    storageProvider: s3_compatible
    bucketName: "cassandra-backup"
    prefix: "test"
    storageSecretRef:
      name: medusa-bucket-key
    host: minio-service.minio.svc.cluster.local
    port: 9000
    secure: false

# Optional: list of external DC names (strings)
externalDatacenters: []

# ExternalSecrets (Vault) integration - only references (no secret content)
externalSecrets:
  enabled: false
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  paths:
    superuser: secret/data/k8ssandra/prod/superuser
    serverTls: secret/data/k8ssandra/prod/tls/server
    clientTls: secret/data/k8ssandra/prod/tls/client
    medusa: secret/data/k8ssandra/prod/medusa
