applicationsets:
  operator-applicationset:
    namespace: argocd
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    generators:
      - git:
          repoURL: https://github.com/FloGerber/argocd-templates.git
          revision: HEAD
          directories:
            - path: appSetWay/apps/*
    ignoreApplicationDifferences:
      - jsonPointers:
          - /spec/syncPolicy
    template:
      metadata:
        name: "{{ path.basename }}"
      spec:
        project: default
        source:
          repoURL: https://github.com/FloGerber/argocd-templates.git
          targetRevision: HEAD
          path: "{{path}}"
        destination:
          server: https://kubernetes.default.svc
          namespace: "{{path.basename}}"
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
    syncPolicy:
      # Set Application finalizer
      preserveResourcesOnDeletion: false
