strimzi-drain-cleaner:
  # Default values for strimzi-drain-cleaner.

  replicaCount: 3

  podDisruptionBudget:
    # Specifies whether a pod disruption budget should be created
    create: true
    minAvailable: 1

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # affinity:
  #   podAntiAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchExpressions:
  #           - key: app
  #             operator: In
  #             values:
  #               - strimzi-drain-cleaner
  #       topologyKey: topology.kubernetes.io/zone
