{{ include "library.configmap" . | nindent 0 }}
---
{{ include "library.secrets" . | nindent 0 }}
---
{{ include "library.deployment" . | nindent 0 }}
---
{{ include "library.service" . | nindent 0 }}
---
{{ include "library.ingress" . | nindent 0 }}
---
{{ include "library.hpa" . | nindent 0 }}
---
{{ include "library.networkPolicy" . | nindent 0 }}
