apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: '{{ .Values.projectName }}-apps-config'
    namespace: {{ .Values.argoNamespace | default "argocd" }}
spec:
    generators:
        - git:
            repoURL: {{ .Values.gitRepo }}
            revision: HEAD
            directories:
                - path: {{ .Values.repoPath }}
    template:
        metadata:
            name: "{{ path.basename }}"
    spec:
        destination:
            namespace: '{{ path.basename }}'
            server: 'https://kubernetes.default.svc'
        project: default
        source:
            repoURL: {{ .Values.gitRepo }}
            targetRevision: HEAD
            path: "{{path}}"
        syncPolicy:
            automated:
                prune: true
                selfHeal: true
