{{- range .Values.subscriptions }}

apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-catalog
  namespace: olm
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  sourceType: grpc
  image: quay.io/operatorhubio/catalog:latest
  displayName: OperatorHub.io Catalog
  publisher: OperatorHub.io

---

{{- if ne .namespace "operators" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2" 

---
{{- end }}

apiVersion: operators.coreos.com/v1alpha2 
kind: OperatorGroup
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec: {}

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name | quote }}
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4" 
spec:
  channel: {{ .channel }}
  installPlanApproval: Automatic
  name: {{ .name }}
  source: {{ .source }}
  sourceNamespace: olm
---

{{- end }}