apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: {{ include "k8ssandra.fullname" . }}
{{- if .Values.labels }}
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ include "k8ssandra.annotations" . | indent 4 }}
{{- end }}
spec:
  {{- if .Values.auth }}
  # Whether authentication is enabled for Cassandra, Reaper, and Medusa.
  # Highly recommended to keep this true.
  auth: {{ .Values.auth | default true }}
  {{- end }}
  {{- if .Values.secretsProvider }}
  # secretsProvider: "internal" (K8s secrets) or "external" (external secret store)
  secretsProvider: {{ .Values.secretsProvider | quote }}
  {{- end }}
  # Cassandra cluster configuration (datacenters, racks, storage, JVM, etc.)
  cassandra:
{{ include "k8ssandra.cassandra" . | indent 4 }}

{{- if ((.Values.reaper).enabled) }}
  # Reaper handles automatic repair scheduling for Cassandra. (optional)
{{ include "k8ssandra.reaper" . | indent 4 }}
{{- end }}

{{- if ((.Values.medusa).enabled) }}
  # Medusa manages backups and restores for Cassandra. (optional)
{{ include "k8ssandra.medusa" . | indent 4 }}
{{- end }}

  {{- if .Values.externalDatacenters }}
  # Optional list of external datacenters (for multi-cluster replication setup).
  externalDatacenters:
{{ toYaml .Values.externalDatacenters | indent 4 }}
  {{- end }}