apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: {{ include "k8ssandra.fullname" . }}
{{- if .Values.labels }}
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ include "k8ssandra.annotations" . | indent 4 }}
{{- end }}
spec:
  # Whether authentication is enabled for Cassandra, Reaper, and Medusa.
  # Highly recommended to keep this true.
  auth: {{ default true .Values.auth.enabled }}
  # secretsProvider: "internal" (K8s secrets) or "external" (external secret store)
  {{- with .Values.secretsProvider }}
  secretsProvider: {{ .Values.secretsProvider | quote }}
  {{- end -}}
  # Cassandra cluster configuration (datacenters, racks, storage, JVM, etc.)
  cassandra:
{{ include "k8ssandra.cassandra" . | indent 4 }}
{{println}}
  # Reaper handles automatic repair scheduling for Cassandra. (optional)
{{- if ((.Values.reaper).enabled) -}}
  reaper:
{{ include "k8ssandra.reaper" . | indent 2 }}
{{- end -}}
{{println}}
  # Medusa manages backups and restores for Cassandra. (optional)
{{- if ((.Values.medusa).enabled) -}}
  medusa:
{{ include "k8ssandra.medusa" . | indent 2 }}
{{- end -}}
{{println}}
  # Optional list of external datacenters (for multi-cluster replication setup).
  {{- if .Values.externalDatacenters }}
  externalDatacenters:
{{ toYaml .Values.externalDatacenters | indent 4 }}
  {{- end }}