## only for local Testing

apiVersion: v1
kind: Secret
metadata:
  name: medusa-bucket-key
type: Opaque
stringData:
  credentials: |-
    [default]
    aws_access_key_id = JwGosLIYIT254Q2zUehm
    aws_secret_access_key = zvkWpe4ofSjoCXUMOhNZghdredZ2O70vLkFItRtt
