global:
  imageRegistry: docker.repo.xxx.xxx # Base URL for all container images
  imagePullPolicy: Always # Default pull policy: Always, IfNotPresent, Never

# Service overrides
photonbg:
  containers:
    - name: photonbg
      image:
        repository: docker.repo.xxx.xxx/servicecatalog/photonbg
        tag: "latest"

positianstream:
  containers:
    - name: positianstream
      image:
        repository: docker.repo.xxx.xxx/servicecatalog/positian-stream
        tag: "latest"

positianui:
  containers:
    - name: positianui
      image:
        repository: docker.repo.xxx.xxx/servicecatalog/positian-ui
        tag: "latest"

roadnetworkservice:
  containers:
    - name: roadnetworkservice
      image:
        repository: docker.repo.xxx.xxx/road-network-service
        tag: "latest"

tcmappingeditor:
  containers:
    - name: tcmappingeditor
      image:
        repository: docker.repo.xxx.xxx/geolocationplatformgroup/tc-mapping-editor
        tag: "latest"

tcmsky:
  containers:
    - name: tcmsky
      image:
        repository: docker.repo.xxx.xxx/servicecatalog/tcm-sky
        tag: "latest"

tcservice:
  containers:
    - name: tcservice
      image:
        repository: docker.repo.xxx.xxx/tolling-engine-xx
        tag: "latest"
    - name: tcservice-tower
      image:
        repository: docker.repo.xxx.xxx/tower
        tag: "latest"
    - name: tcservice-linker
      image:
        repository: docker.repo.xxx.xxx/tc-mapping-linker
        tag: "latest"
  initContainers:
    - name: tcservice-init
      image:
        repository: docker.repo.xxx.xxx/tower
        tag: "latest"

tileserver:
  containers:
    - name: tileserver
      image:
        repository: docker.repo.xxx.xxx/httpcache
        tag: "latest"
    - name: tileserver-sidecar
      image:
        repository: docker.repo.xxx.xxx/tileserver-gl
        tag: "latest"

tracker:
  containers:
    - name: tracker
      image:
        repository: docker.repo.xxx.xxx/geolocationplatformgroup/tracker
        tag: "latest"

tripbuilder:
  containers:
    - name: tripbuilder
      image:
        repository: docker.repo.xxx.xxx/ervicecatalog/trip-builder
        tag: "latest"
  initContainers:
    - name: tripbuilder-init
      image:
        repository: docker.repo.xxx.xxx/
        tag: "latest"
