## Kafka Cluster Resources

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafkaCluster.name }}
  namespace: {{ .Values.kafkaCluster.namespace }}
  annotations:
    {{- range $key, $value := .Values.kafkaCluster.annotations }}
    strimzi.io/{{ $key }}: {{ $value  }}
    {{- end }}
spec:
  kafka:
    version: {{ .Values.kafkaCluster.version }}
    metadataVersion: {{ .Values.kafkaCluster.metadataVersion }}
    {{- if .Values.kafkaCluster.listeners }}
    listeners:
      {{- range .Values.kafkaCluster.listeners }}
      - name: {{ .name }}
        port: {{ .port }}
        type: {{ .type }}
        tls: {{ .tls }}
      {{- end }}
    {{- end }}
    {{- if .Values.kafkaCluster.config }}
    config:
      {{- range $key, $value := .Values.kafkaCluster.config }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
    {{- if .Values.kafkaCluster.resources }}
    resources:
      {{- toYaml .Values.kafkaCluster.resources | nindent 6 }}
    {{- end }}
    {{- if .Values.kafkaCluster.logging }}
    logging:
      type: inline
      loggers:
        {{- range $key, $value := .Values.kafkaCluster.logging }}
        {{ $key }}: {{ $value }}
        {{- end }}
    {{- end }}
    {{- if .Values.kafkaCluster.readinessProbe }}
    readinessProbe:
      {{- toYaml .Values.kafkaCluster.readinessProbe | nindent 6 }}
    {{- end }}
    {{- if .Values.kafkaCluster.livenessProbe }}
    livenessProbe:
      {{- toYaml .Values.kafkaCluster.livenessProbe | nindent 6 }}
    {{- end }}
    {{- if .Values.kafkaCluster.jvmOptions }}
    jvmOptions:
      {{- range $key, $value := .Values.kafkaCluster.jvmOptions }}
      "{{ $key }}": "{{ $value }}"
      {{- end }}
    {{- end }}
    {{- if .Values.kafkaCluster.authorization }}
    authorization:
      {{- toYaml .Values.kafkaCluster.authorization | nindent 6 }}
    {{- end }}

  {{- if .Values.kafkaCluster.entityOperator.enabled }}
  entityOperator:
    {{- if .Values.kafkaCluster.entityOperator.topicOperator }}
    topicOperator:
      {{- toYaml .Values.kafkaCluster.entityOperator.topicOperator | nindent 6 }}
    {{- end }}
    {{- if .Values.kafkaCluster.entityOperator.userOperator }}
    userOperator:
      {{- toYaml .Values.kafkaCluster.entityOperator.userOperator | nindent 6 }}
    {{- end }}
  {{- end }}

  {{- if .Values.kafkaCluster.kafkaExporter.enabled }}
  kafkaExporter:
    topicRegex: {{ .Values.kafkaCluster.kafkaExporter.topicRegex | quote }}
    groupRegex: {{ .Values.kafkaCluster.kafkaExporter.groupRegex | quote }}
  {{- end }}

  {{- if .Values.kafkaCluster.cruiseControl.enabled }}
  cruiseControl:
    autoRebalance:
      {{- range .Values.kafkaCluster.cruiseControl.templates }}
      - mode: {{ if hasPrefix .name "add" }}add-brokers{{ else }}remove-brokers{{ end }}
        template:
          name: {{ .name }}
      {{- end }}
  {{- end }}
---
