{{- range .Values.kafkaCluster.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
    name: {{ .name }}
    labels:
        strimzi.io/cluster: {{ $.Values.kafkaCluster.name }}
spec:
    {{- if .partitions }}
    partitions: {{ .partitions }}
    {{- end }}
    {{- if .replicas }}
    replicas: {{ .replicas }}
    {{- end }}
    {{- if .config }}
    config:
        {{- range $key, $value := .config }}
        {{ $key }}: {{ $value }}
        {{- end }}
    {{- end }}
---
{{- end }}