{{- range .Values.kafkaUsers }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: {{ .cluster }}
spec:
  authentication:
    type: {{ .authentication.type }}
  {{- if .template }}
  template:
    secret:
      metadata:
        {{- if .template.secret.metadata.labels }}
        labels:
{{ toYaml .template.secret.metadata.labels | indent 10 }}
        {{- end }}
        {{- if .template.secret.metadata.annotations }}
        annotations:
{{ toYaml .template.secret.metadata.annotations | indent 10 }}
        {{- end }}
  {{- end }}
  {{- if .authorization }}
  authorization:
    type: {{ .authorization.type }}
    acls:
      {{- range .authorization.acls }}
      - resource:
          type: {{ .resource.type }}
          name: {{ .resource.name }}
          patternType: {{ .resource.patternType }}
        operations:
          {{- range .operations }}
          - {{ . }}
          {{- end }}
        host: {{ .host | quote }}
      {{- end }}
  {{- end }}
  {{- if .quotas }}
  quotas:
    {{- if .quotas.producerByteRate }}
    producerByteRate: {{ .quotas.producerByteRate }}
    {{- end }}
    {{- if .quotas.consumerByteRate }}
    consumerByteRate: {{ .quotas.consumerByteRate }}
    {{- end }}
    {{- if .quotas.requestPercentage }}
    requestPercentage: {{ .quotas.requestPercentage }}
    {{- end }}
    {{- if .quotas.controllerMutationRate }}
    controllerMutationRate: {{ .quotas.controllerMutationRate }}
    {{- end }}
  {{- end }}
---
{{- end }}
