app: positianui
deployment_commit: 09df525f
deployment_ref: xx-14530-be--env01

replicaCount: 1
image:
  repository: docker.repo.xxx.xxx/servicecatalog/positian-ui
  tag: 3.30.4-saas-202509010623

containerPorts:
  - name: serviceport
    port: 8080
    protocol: TCP

env:
  - name: HOST
  - name: BASE_URL
    value: /x/xx/glpview/
  - name: FEATURE_FLAGS_API_URL
    value: https://api-dev-sx.x.x.x/x/xx/
  - name: SINK_API_URL
    value: https://api-dev-sx.x.x.x/x/xx/glpdatasink/
  - name: NETWORK_API_URL
    value: https://api-dev-sx.x.x.x/x/xx/roadnetwork/europe/
  - name: AUTHORIZATION_BASE_URL
    value: https://api-dev-sx.x.x.x/x/xx/
  - name: TRACKER_API_URL
    value: https://api-dev-sx.x.x.x/x/xx/tracker/
  - name: INITIAL_MAP_ZOOMLEVEL
    value: "8"
  - name: INITIAL_MAP_CENTER_LAT
    value: "42.664261"
  - name: INITIAL_MAP_CENTER_LON
    value: "25.249328"
  - name: OAUTH2_CLIENT_ID
    value: f5027abd-face-4655-94af-ce83cee63f62
  - name: OAUTH2_SCOPE
    value: openid offline_access f5027abd-face-4655-94af-ce83cee63f62
  - name: OAUTH2_TOKEN_FORWARDING
    value: "true"
  - name: OAUTH2_ERROR_PAGE_URL
    value: https://www-dev-sx.x.x.x/x/xx/userflow_feedback.html
  - name: OAUTH2_DISCOVERY_DOCUMENT_URL
    value: https://xxx.b2clogin.com/xxx/v2.0/.well-known/openid-configuration?p=xxx
  - name: DETECTION_CONFIDENCE_THRESHOLD
    value: "0.79"
  - name: CHARGE_OBJECTS_LAYER_VISIBILITY_THRESHOLD
    value: "10000"
  - name: BASE_LAYER1
    value: Tile server,https://api-dev-sx.x.x.x/x/xx/tiles/english/{z}/{x}/{y}.png?apikey=xPVLlZNxxxx3bC,,no-token
  - name: BASE_LAYER2
  - name: BASE_LAYER3
  - name: BASE_LAYER4
  - name: DEVICES_POLLING_INTERVAL_SECONDS
    value: "5"
  - name: OFFLINE_DEVICE_INTERVAL_MINUTES
    value: "5"
  - name: MAX_RESULTS_POSITIONS
    value: "12000"
  - name: MAX_RESULTS_SEGMENTS
    value: "8000"
  - name: MAX_RESULTS_CHARGE_OBJECTS
    value: "6400"
  - name: TOLL_CONTEXT_CONFIG_LOCATION
    value: /config/ui-toll-context-config.json

resources:
  limits:
    cpu: 100m
    memory: 64Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 33m
    memory: 64Mi
    ephemeral-storage: 1Gi

lifecycle:
  preStop:
    exec:
      command: ["sleep", "20"]

livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 3
  periodSeconds: 20
  timeoutSeconds: 20
  successThreshold: 1
  failureThreshold: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 3
  periodSeconds: 20
  timeoutSeconds: 20
  successThreshold: 1
  failureThreshold: 5

startupProbe:
  httpGet:
    path: /healthz
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 3
  periodSeconds: 20
  timeoutSeconds: 20
  successThreshold: 1
  failureThreshold: 4

hostAliases:
  - ip: x.x.x.x
    hostnames:
      - xxxxx.blob.core.windows.net
      - xxxxx-secondary.blob.core.windows.net
      - xxxx.blob.core.windows.net
      - xxxx.redis.cache.windows.net

terminationGracePeriodSeconds: 60

volumeMounts:
  - mountPath: /config
    name: config
    readOnly: true

volumes:
  - name: config
    configMap:
      name: positianui-files
      defaultMode: 420

configmap:
  binaryData:
    ui-toll-context-config.json: xxx=

service:
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  ipFamily: IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: serviceport
      port: 8001
      protocol: TCP
      targetPort: 8080

ingress:
  enabled: true
  host: www-dev-sx.x.x.x
  path: /x/xx/glpview(.*)
  serviceName: positianui
  servicePort: 8001
  proxyBodySize: 8m
  rewriteTarget: /$1
  sslRedirect: "false"

networkPolicy:
  enabled: true
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              nsname: k8sinfra
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
        - podSelector:
            matchLabels:
              app: k8s-ansible-helper
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              kubernetes.azure.com/managedby: aks
      ports:
        - port: 8080
          protocol: TCP
  egress:
    - ports:
        - port: 53
          protocol: UDP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              k8s-app: kube-dns
