apiVersion: v2
name: kdp-velero
description: velero.

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1
appVersion: "1.16.1"

# pull in external charts via dependencies:
# Strimzi Operator helm chart
dependencies:
  - name: velero
    version: 10.0.8
    repository: https://vmware-tanzu.github.io/helm-charts
