{{- range .Values["strimzi-kafka-operator"].watchNamespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
    name: {{ . }}
    annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
{{- end }}