fullnameOverride: tcmappingeditor

deployment:
  enabled: true
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/publicEndpoints: '[{"addresses":["x.x.x.x"],"port":80,"protocol":"HTTP","serviceName":"xx-xx-development--env03:tcmappingeditor","ingressName":"xx-xx-development--env03:tcmappingeditor","hostname":"www-dev-sx.x.x.x","path":"/x/xx/tc-mapping-editor(.*)","allNodes":false}]'
  podAnnotations:
    redeploytrigger: xxx
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - tcmappingeditor
            topologyKey: topology.kubernetes.io/zone
        - weight: 5
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - tcmappingeditor
            topologyKey: kubernetes.io/hostname
  hostAliases:
    - ip: x.x.x.x
      hostnames:
        - xxxxx.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxxx-secondary.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxx.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxx.redis.cache.windows.net
  terminationGracePeriodSeconds: 60
  serviceAccount:
    automount: false

containers:
  - name: tcmappingeditor
    image:
      repository: xx
      tag: xx
    imagePullPolicy: Always
    ports:
      - name: serviceport
        containerPort: 8080
        protocol: TCP
    env:
      - name: HOST
      - name: APP_BASE_URL
        value: /x/xx/tc-mapping-editor/
      - name: FEATURE_FLAGS_API_URL
        value: https://api-dev-sx.x.x.x/x/xx/
      - name: NETWORK_API_URL
        value: https://api-dev-sx.x.x.x/x/xx/roadnetwork/europe/
      - name: AUTHORIZATION_BASE_URL
        value: https://api-dev-sx.x.x.x/x/xx/
      - name: OAUTH2_ENABLED
        value: "true"
      - name: OAUTH2_CLIENT_ID
        value: 6axxxx
      - name: OAUTH2_SCOPE
        value: openid offline_access 6axxxxx
      - name: OAUTH2_TOKEN_FORWARDING
        value: "true"
      - name: OAUTH2_ERROR_PAGE_URL
        value: https://www-dev-sx.x.x.x/x/xx/userflow_feedback.html
      - name: OAUTH2_DISCOVERY_DOCUMENT_URL
        value: https://xxx.b2clogin.com/xxx/v2.0/.well-known/openid-configuration?p=xxx
      - name: TOLL_CONTEXT_CONFIG_LOCATION
        value: /config/ui-toll-context-config.json
      - name: MAP_REGION
        value: europe
      - name: DETAIL_THRESHOLD_RESOLUTION
        value: "50"
      - name: NO_SHOW_THRESHOLD_RESOLUTION
        value: "45000000"
      - name: BASE_LAYER1
        value: Tile server,https://api-dev-sx.x.x.x/x/xx/tiles/english/{z}/{x}/{y}.png?apikey=xxxx,,no-token
      - name: BASE_LAYER2
      - name: BASE_LAYER3
      - name: BASE_LAYER4
    lifecycle:
      preStop:
        exec:
          command: ["sleep", "20"]
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
        ephemeral-storage: 1Gi
      requests:
        cpu: 33m
        memory: 64Mi
        ephemeral-storage: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
    probes:
      liveness:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 10
      readiness:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 5
      startup:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 4
    volumeMounts:
      - name: config
        mountPath: /config
        readOnly: true

volumes:
  - name: config
    configMap:
      name: tcmappingeditor-files
      defaultMode: 420

configmap:
  enabled: true
  binaryData:
    ui-toll-context-config.json: xxxx=

service:
  enabled: true
  type: ClusterIP
  clusterIP: x.x.x.x
  ports:
    - name: serviceport
      port: 8091
      targetPort: 8080
      protocol: TCP
  sessionAffinity: None

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: www-dev-sx.x.x.x
      paths:
        - path: /x/xx/tc-mapping-editor(.*)
          pathType: Prefix
          servicePort: 8091

networkPolicy:
  enabled: true
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app: tcmappingeditor
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              nsname: k8sinfra
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
        - podSelector:
            matchLabels:
              app: k8s-ansible-helper
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              kubernetes.azure.com/managedby: aks
      ports:
        - port: 8080
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
