fullnameOverride: glpdatasink

deployment:
  enabled: true
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  annotations:
    deployment.kubernetes.io/revision: "1"
  podAnnotations:
    prometheus.io/path: /manage/prometheus
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
    redeploytrigger: xxxx
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - glpdatasink
            topologyKey: topology.kubernetes.io/zone
        - weight: 5
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - glpdatasink
            topologyKey: kubernetes.io/hostname
  hostAliases:
    - ip: x.x.x.x
      hostnames:
        - xxxxx.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxxx-secondary.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxx.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxx.redis.cache.windows.net
  terminationGracePeriodSeconds: 60
  serviceAccount:
    automount: false

containers:
  - name: glpdatasink
    image:
      repository: xx
      tag: xx
    imagePullPolicy: Always
    ports:
      - name: serviceport
        containerPort: 8080
        protocol: TCP
    env:
      - name: SERVER_PORT
        value: "8080"
      - name: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=60.0 -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -XX:+UseStringDeduplication
      - name: MANAGEMENT_SERVER_PORT
        value: "8081"
      - name: SERVER_SERVLET_CONTEXT_PATH
        value: /glpdatasink
      - name: KAFKA_CONSUMER_CHARGEREPORTTOPIC_NAME
        value: charge-report
      - name: KAFKA_CONSUMER_CHARGINGPOSITIONTOPIC_NAME
        value: charging-position
      - name: KAFKA_CONSUMER_MATCHEDPOSITIONTOPIC_NAME
        value: matched-position
      - name: KAFKA_CONSUMER_MATCHEDROUTETOPIC_NAME
        value: matched-route
      - name: KAFKA_CONSUMER_CONCURRENCY
        value: "128"
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: xxxx.servicebus.windows.net:9093
      - name: SPRING_CASSANDRA_CONTACT_POINTS
        value: xxxx.cassandra.cosmos.azure.com
      - name: SPRING_CASSANDRA_PORT
        value: "10350"
      - name: SPRING_CASSANDRA_KEYSPACE_NAME
        value: glpdatasink
      - name: SPRING_CASSANDRA_LOCAL_DATACENTER
        value: xxx
      - name: CASSANDRA_CUSTOM_DEVICE_REFRESH_INTERVAL
        value: "5000"
      - name: CASSANDRA_CUSTOM_MAX_CONNECTIONS_PER_HOST
        value: "120"
      - name: CASSANDRA_CUSTOM_AUTOSCALE_MAX_THROUGHPUT
        value: "5000"
      - name: CASSANDRA_CUSTOM_BUCKET_COUNT
        value: "8"
      - name: CASSANDRA_CUSTOM_MIGRATION_ENABLED
        value: "false"
      - name: CASSANDRA_CUSTOM_MIGRATION_ONLY
        value: "false"
      - name: CASSANDRA_CUSTOM_TTL_CHARGING_POSITION
        value: P45D
      - name: CASSANDRA_CUSTOM_TTL_MATCHED_SEGMENT
        value: P45D
      - name: CASSANDRA_CUSTOM_TTL_CHARGE_REPORT
        value: P45D
      - name: CASSANDRA_CUSTOM_TTL_AGGREGATED_KPI
        value: P45D
      - name: CASSANDRA_CUSTOM_TTL_MATCHED_POSITION
        value: P45D
      - name: LOGGING_LEVEL_COM_XXX
        value: INFO
    envFrom:
      - secretRef:
          name: glpdatasink-secret
    lifecycle:
      preStop:
        exec:
          command: ["sleep", "20"]
    resources:
      limits:
        cpu: 500m
        memory: 1280Mi
        ephemeral-storage: 1Gi
      requests:
        cpu: 166m
        memory: 1280Mi
        ephemeral-storage: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
    probes:
      liveness:
        httpGet:
          path: /manage/health
          port: 8081
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 10
      readiness:
        httpGet:
          path: /manage/health
          port: 8081
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 5
      startup:
        httpGet:
          path: /manage/health
          port: 8081
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 13

initContainers:
  - name: glpdatasink-init
    image:
      repository: xx
      tag: xx
    imagePullPolicy: Always
    env:
      - name: SERVER_PORT
        value: "8080"
      - name: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=60.0 -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -XX:+UseStringDeduplication
      - name: MANAGEMENT_SERVER_PORT
        value: "8081"
      - name: SERVER_SERVLET_CONTEXT_PATH
        value: /glpdatasink
      - name: KAFKA_CONSUMER_CHARGEREPORTTOPIC_NAME
        value: charge-report
      - name: KAFKA_CONSUMER_CHARGINGPOSITIONTOPIC_NAME
        value: charging-position
      - name: KAFKA_CONSUMER_MATCHEDPOSITIONTOPIC_NAME
        value: matched-position
      - name: KAFKA_CONSUMER_MATCHEDROUTETOPIC_NAME
        value: matched-route
      - name: KAFKA_CONSUMER_CONCURRENCY
        value: "128"
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: xxxx.servicebus.windows.net:9093
      - name: SPRING_CASSANDRA_CONTACT_POINTS
        value: xxxx.cassandra.cosmos.azure.com
      - name: SPRING_CASSANDRA_PORT
        value: "10350"
      - name: SPRING_CASSANDRA_KEYSPACE_NAME
        value: glpdatasink
      - name: SPRING_CASSANDRA_LOCAL_DATACENTER
        value: xxx
      - name: CASSANDRA_CUSTOM_MIGRATION_ENABLED
        value: "true"
      - name: CASSANDRA_CUSTOM_MIGRATION_ONLY
        value: "true"
      - name: CASSANDRA_CUSTOM_DEVICE_REFRESH_INTERVAL
        value: "5000"
      - name: CASSANDRA_CUSTOM_MAX_CONNECTIONS_PER_HOST
        value: "120"
      - name: CASSANDRA_CUSTOM_AUTOSCALE_MAX_THROUGHPUT
        value: "5000"
      - name: CASSANDRA_CUSTOM_BUCKET_COUNT
        value: "8"
      - name: CASSANDRA_CUSTOM_TTL_CHARGING_POSITION
        value: P45D
      - name: CASSANDRA_CUSTOM_TTL_MATCHED_SEGMENT
        value: P45D
      - name: CASSANDRA_CUSTOM_TTL_CHARGE_REPORT
        value: P45D
      - name: CASSANDRA_CUSTOM_TTL_AGGREGATED_KPI
        value: P45D
      - name: CASSANDRA_CUSTOM_TTL_MATCHED_POSITION
        value: P45D
      - name: LOGGING_LEVEL_COM_XXX
        value: INFO
    envFrom:
      - secretRef:
          name: glpdatasink-initcontainer-secret
    resources:
      limits:
        cpu: 500m
        memory: 1280Mi
        ephemeral-storage: 1Gi
      requests:
        cpu: 166m
        memory: 1280Mi
        ephemeral-storage: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
