fullnameOverride: mtd

deployment:
  enabled: true
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  annotations:
    deployment.kubernetes.io/revision: "1"
  podAnnotations:
    prometheus.io/path: /manage/prometheus
    prometheus.io/port: "18052"
    prometheus.io/scrape: "true"
    redeploytrigger: b2559c4c06a3519ef16cb14f7bba846040cd8140
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - mtd
            topologyKey: topology.kubernetes.io/zone
        - weight: 5
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - mtd
            topologyKey: kubernetes.io/hostname
  hostAliases:
    - ip: x.x.x.x
      hostnames:
        - xxxxx.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxxx-secondary.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxx.blob.core.windows.net
    - ip: x.x.x.x
      hostnames:
        - xxxx.redis.cache.windows.net
  terminationGracePeriodSeconds: 60
  serviceAccount:
    automount: false

containers:
  - name: mtd
    image:
      repository: xx
      tag: xx
    imagePullPolicy: Always
    ports:
      - name: serviceport
        containerPort: 8010
        protocol: TCP
    env:
      - name: SERVER_PORT
        value: "8010"
      - name: MANAGEMENT_SERVER_PORT
        value: "18052"
      - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: health,prometheus
      - name: MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED
        value: "true"
      - name: SPRING_PROFILES_ACTIVE
        value: glpn,photon
      - name: HANDLER_CHARGE_OBJECT_MAPPING_URL
        value: http://tcservicebg:8077
      - name: HANDLER_RATE_URL
        value: http://tcservicebg:8050
      - name: ROUTE_GLPN_URL
        value: http://roadnetworkservice:8090/roadnetwork/europe
      - name: ROUTE_GLPN_MAX_DISTANCE
        value: "500"
      - name: GEOCODER_PHOTON_SEARCH_URL
        value: http://photonbg:2322
      - name: LOGGING_LEVEL_COM_XXX
        value: ERROR
      - name: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=80.0 -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -XX:+UseStringDeduplication
    lifecycle:
      preStop:
        exec:
          command: ["sleep", "20"]
    resources:
      limits:
        cpu: 300m
        memory: 768Mi
        ephemeral-storage: 1Gi
      requests:
        cpu: 100m
        memory: 768Mi
        ephemeral-storage: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
    probes:
      liveness:
        httpGet:
          path: /manage/health
          port: 18052
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 10
      readiness:
        httpGet:
          path: /manage/health
          port: 18052
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 5
      startup:
        httpGet:
          path: /manage/health
          port: 18052
        initialDelaySeconds: 3
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 9

service:
  enabled: true
  type: ClusterIP
  ports:
    - name: serviceport
      port: 8010
      targetPort: 8010
      protocol: TCP
    - name: healthport
      port: 18052
      targetPort: 18052
      protocol: TCP
  sessionAffinity: None

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: ContainerResource
      containerResource:
        container: mtd
        name: cpu
        target:
          type: AverageValue
          averageValue: 210m
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      selectPolicy: Max
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 180

networkPolicy:
  enabled: true
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app: mtd
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: k8s-ansible-helper
        - podSelector:
            matchLabels:
              app: kong
      ports:
        - port: 8010
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              kubernetes.azure.com/managedby: aks
        - podSelector:
            matchLabels:
              app: k8s-ansible-helper
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              kubernetes.azure.com/managedby: aks
        - podSelector:
            matchLabels:
              app: k8s-ansible-helper
      ports:
        - port: 18052
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - podSelector:
            matchLabels:
              app: tcservicebg
      ports:
        - port: 8819
          protocol: TCP
        - port: 8050
          protocol: TCP
        - port: 8077
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: roadnetworkservice
      ports:
        - port: 8090
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: photonbg
      ports:
        - port: 2322
          protocol: TCP
