apiVersion: v2
name: chargereportserver
description: Helm Chart for chargereportserver service.

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.6
appVersion: "0.0.1" #  version.

dependencies:
  - name: library
    version: 0.0.13
    repository: file://../library
